import { defineConfig } from "oxlint";

export default defineConfig({
  env: {
    browser: true,
  },
  categories: {
    correctness: "error",
    pedantic: "error",
    perf: "error",
    suspicious: "error",
  },
  options: {
    typeAware: true,
    typeCheck: true,
  },
  plugins: ["import", "typescript", "promise", "unicorn"],
  rules: {
    "@typescript-eslint/await-thenable": "error",
    "@typescript-eslint/consistent-type-imports": ["error", { prefer: "type-imports" }],
    "@typescript-eslint/explicit-function-return-type": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-floating-promises": "error",
    "@typescript-eslint/no-for-in-array": "error",
    "@typescript-eslint/no-implied-eval": "error",
    "@typescript-eslint/no-misused-promises": "error",
    "@typescript-eslint/no-non-null-assertion": "error",
    "@typescript-eslint/no-unsafe-argument": "error",
    "@typescript-eslint/no-unsafe-assignment": "error",
    "@typescript-eslint/no-unsafe-call": "error",
    "@typescript-eslint/no-unsafe-member-access": "error",
    "@typescript-eslint/no-unsafe-return": "error",
    "@typescript-eslint/restrict-plus-operands": "error",
    "@typescript-eslint/restrict-template-expressions": "error",
    "@typescript-eslint/strict-boolean-expressions": "error",
    "@typescript-eslint/switch-exhaustiveness-check": "error",
    "@typescript-eslint/unbound-method": "error",
    "typescript/prefer-readonly-parameter-types": [
      "error",
      {
        allow: [
          {
            from: "lib",
            name: [
              "Attr",
              "CharacterData",
              "Comment",
              "Document",
              "DocumentFragment",
              "DocumentType",
              "Element",
              "Event",
              "EventTarget",
              "HTMLElement",
              "HTMLAnchorElement",
              "HTMLAudioElement",
              "HTMLButtonElement",
              "HTMLDivElement",
              "HTMLInputElement",
              "HTMLLabelElement",
              "HTMLSelectElement",
              "HTMLSpanElement",
              "HTMLTextAreaElement",
              "Map",
              "MouseEvent",
              "MutationRecord",
              "Node",
              "ParentNode",
              "Range",
              "ReadonlyMap",
              "ReadonlySet",
              "Set",
              "Text",
            ],
          },
          {
            from: "file",
            name: [
              "AtomCounter",
              "MatchingState",
              "MlgBoundary",
              "MlgMessage",
              "PageMatcher",
              "PendingBlock",
              "TokenBuildState",
              "TokenStream",
              "TokenStreamItem",
            ],
          },
          {
            from: "package",
            name: ["BrowserContext"],
            package: "playwright-core",
          },
        ],
        ignoreInferredTypes: true,
      },
    ],
  },
});
